### ISSUE TITLE
Tests fail if IO::Socket::SSL is not installed

### ISSUE THREAD

**Issue by eserte** [LibreCat/Catmandu-ArXiv#1]
See subject. Test log:
```
SSL requires IO::Socket::SSL, but it is not available. Please install IO::Socket::SSL using your prefer CPAN client at /tmpfs/.cpan-build-cpansand/2017030318/Catmandu-ArXiv-0.100-sQaSfX/blib/lib/Catmandu/Importer/ArXiv.pm line 37.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 7.
t/01-import.t .......... 
Dubious, test returned 2 (wstat 512, 0x200)
All 7 subtests passed 
```

**Comment by vpeil** [comment]
I think I don't  need SSL anywhere. I am a bit confused.

**Comment by phochste** [comment]
@vpeil You didn't specify which Catmandu version works with Catmandu-ArXiv. Maybe there are old versions that needed this extra dependancy. Try to update cpanfile with the mininal required versions of the dependencies

**Comment by vpeil** [comment]
I've pushed another version some days ago. But I can't see any reports for this:
http://www.cpantesters.org/distro/C/Catmandu-ArXiv.html#Catmandu-ArXiv-0.101

**Comment by eserte** [comment]
Looks good, currently only passes for perl >= 5.10.1: http://fast-matrix.cpantesters.org/?dist=Catmandu-ArXiv-0.101
