### ISSUE TITLE
URLs hardcoded in the Arxiv importer

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-ArXiv#3]
When I was testing the LibreCat I found out it was impossible to mimic Arxiv interactions without having network access. The sole reason for this is because the "https://arxiv.org/a/" is hardcoded in the package and can't be changed to another address. Would it be possible to make this URL configurable?

https://github.com/LibreCat/Catmandu-ArXiv/blob/master/lib/Catmandu/Importer/ArXiv.pm#L48

**Comment by vpeil** [comment]
of course, will do this asap.

**Comment by vpeil** [comment]
fixed by cc518a4f15a49423e296d66e8cd6548029953244.

Released to cpan one minute ago.
